
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MAX_WORKERS=8
      - CORS_ORIGINS=http://localhost:3000
      - MODEL_TIMEOUT=45
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2GB
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
